name: CD Deploy to Azure staging

on:
  workflow_dispatch:
  push:
    branches: dev

jobs:
  deploy:
    name: "Deploy functions App to staging slot"
    uses: parloa/workflows/.github/workflows/cs-deployment-func.yaml@main
    with:
      AZURE_FUNCTIONAPP_NAME: 'parloa-github-cd'
      SLOT_NAME: 'staging'
    secrets:
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_STAGING }}
